site_name: Technical Theatre Wiki
site_description: A wiki for the Technical Theatre Society at the University of York
site_author: University of York's Technical Theatre Society et all
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yorktechsoc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UoYTechSoc

copyright: "Made with <3 by York Tech Soc"

repo_url: https://github.com/yorktechsoc/wiki
