// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Docusaurus generated sidebar
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
